// Generated by CoffeeScript 1.7.1
var Service;

Service = {};

Service.ensureAuthenticated = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    res.statusCode = 401;
    return res.send({
      error: "Unauthorized"
    });
  }
};

module.exports = Service;
