// Generated by CoffeeScript 1.7.1
var app, assets, bodyParser, config, cookieParser, dbConfig, env, express, mongoose, partials, path, routes, sassMiddleware, session;

express = require('express');

assets = require('connect-assets');

partials = require('express-partials');

session = require('express-session');

mongoose = require('mongoose');

cookieParser = require('cookie-parser');

bodyParser = require('body-parser');

sassMiddleware = require('node-sass-middleware');

path = require('path');


/*
Initialization
 */

app = express();

app.port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

env = process.env.NODE_ENV || 'development';

config = require('./config');

config.setEnvironment(env);

dbConfig = '';

if (env === 'production') {
  mongoose.connect(dbConfig);
} else {
  mongoose.connect('mongodb://localhost/example');
}


/*
View initialization
 */

app.use(assets());

app.use(express["static"](path.join(__dirname, 'assets/stylesheets')));

app.use(express["static"](path.join(__dirname, 'assets/javascripts')));

app.use(express["static"](path.join(__dirname, 'vendor/javascripts')));

app.use(express["static"](path.join(__dirname, 'vendor/stylesheets')));

app.use(express["static"](path.join(__dirname, 'public')));

app.use(sassMiddleware({
  src: path.join(__dirname.replace('app', 'src'), 'assets/stylesheets'),
  dest: path.join(__dirname, 'assets/stylesheets'),
  debug: true
}));

console.log('setting session/cookie');

app.use(cookieParser());

app.use(session({
  secret: '2345876yt89gubvowtuye8obgsv7uo8fi',
  key: 'sid',
  cookie: {
    secure: true
  }
}));

app.set('view engine', 'jade');

app.use(partials());

app.use(bodyParser());


/*
Finalization
 */

routes = require('./routes');

routes(app);

module.exports = app;
