// Generated by CoffeeScript 1.7.1
var createApiRoutes;

module.exports = function(app) {
  createApiRoutes(app, 'notes');
  return app.all('/*', function(request, response) {
    return response.render('index', {
      layout: false
    });
  });
};

createApiRoutes = function(app, resource, version) {
  var required;
  if (version == null) {
    version = 1;
  }
  required = require("./controllers/api/v" + version + "/" + resource);
  app.get("api/v" + version + "/" + resource, required.index);
  app.get("api/v" + version + "/" + resource + "/:id", required.show);
  app.post("api/v" + version + "/" + resource, required.create);
  app.put("api/v" + version + "/" + resource + "/:id", required.update);
  return app["delete"]("api/v" + version + "/" + resource + "/:id", required["delete"]);
};
