// Generated by CoffeeScript 1.7.1
var Note;

Note = require('../../../models/note');

module.exports = {
  index: function(request, response) {
    return Note.find({}, function(error, notes) {
      return response.send(notes);
    });
  },
  show: function(request, response) {
    return Note.findById(request.params.id, function(error, note) {
      if (!error) {
        return response.send(note);
      } else {
        response.send(error);
        return response.statusCode = 500;
      }
    });
  },
  create: function(request, response) {
    var note;
    note = new Note(request.body);
    return note.save(function(error, note) {
      if (!error) {
        response.send(note);
        return response.statusCode = 201;
      } else {
        response.send(error);
        return response.statusCode = 500;
      }
    });
  },
  update: function(request, response) {
    return Note.findByIdAndUpdate(request.params.id, {
      $set: request.body
    }, function(error, note) {
      if (!error) {
        return response.send(note);
      } else {
        response.send(error);
        return response.statusCode = 500;
      }
    });
  },
  "delete": function(request, response) {
    return Note.findByIdAndRemove(request.params.id, function(error) {
      if (!error) {
        return response.send({});
      } else {
        response.send(error);
        return response.statusCode = 500;
      }
    });
  }
};
