// Generated by CoffeeScript 1.7.1
module.exports = function(app, Note, userService) {
  app.get('/api/v1/notes/', userService.ensureAuthenticated, function(request, response) {
    return Note.findAll().then(function(notes) {
      notes = notes || [];
      return response.json({
        notes: notes
      });
    });
  });
  app.post('/api/v1/notes/', userService.ensureAuthenticated, function(request, response) {
    return Note.create(request.body).then(function(note) {
      response.json(note);
      return response.statusCode = 201;
    })["catch"](function(error) {
      response.send(error);
      return response.statusCode = 500;
    });
  });
  app.put('/api/v1/notes/:id', userService.ensureAuthenticated, function(request, response) {
    return Note.findById(request.params.id).then(function(note) {
      if (note) {
        return note.updateAttributes(request.body).then(function(note) {
          return response.json(note);
        })["catch"](function(error) {
          response.send(error);
          return response.statusCode = 500;
        });
      } else {
        response.statusCode = 500;
        return response.send({
          error: "Resource not found"
        });
      }
    });
  });
  app.get('/api/v1/notes/:id', userService.ensureAuthenticated, function(request, response) {
    return Note.findById(request.params.id).then(function(note) {
      if (note) {
        return response.json(note);
      } else {
        response.statusCode = 500;
        return response.send({
          error: "Resource not found"
        });
      }
    })["catch"](function(error) {
      response.statusCode = 500;
      return response.send(error);
    });
  });
  return app["delete"]('/api/v1/notes/:id', userService.ensureAuthenticated, function(request, response) {
    return Note.findById(request.params.id).then(function(note) {
      if (note) {
        return note.destroy().then(function(note) {
          return response.json({});
        })["catch"](function(error) {
          response.send(error);
          return response.statusCode = 500;
        });
      } else {
        response.statusCode = 500;
        return response.send({
          error: "Resource not found"
        });
      }
    });
  });
};
