// Generated by CoffeeScript 1.7.1
module.exports = function(app, Users) {
  return app.post('/api/v1/users/', function(request, response) {
    return Users.create({
      email: request.body.email,
      password: request.body.password,
      firstName: request.body.firstName,
      lastName: request.body.lastName,
      username: request.body.username
    }, function(err, user) {
      if (err) {
        if (err.code === 11000) {
          response.json({
            errors: {
              unique: "Username and email must be unique"
            }
          });
        }
        throw err;
      }
      return response.json(user);
    });
  });
};
