// Generated by CoffeeScript 1.7.1
module.exports = function(mongoose) {
  var Note;
  Note = new mongoose.Schema({
    order: Number,
    title: String,
    content: String,
    author: String,
    created: {
      type: Date,
      "default": Date.now
    }
  });
  return mongoose.model('Note', Note);
};
