// Generated by CoffeeScript 1.7.1
var Hash;

Hash = require('password-hash');

module.exports = function(mongoose, passportLocal) {
  var User;
  User = new mongoose.Schema({
    email: {
      unique: true,
      required: 'Email is required',
      type: String
    },
    firstName: String,
    lastName: String,
    username: {
      unique: true,
      type: String,
      required: 'Username is required'
    },
    password: {
      type: String,
      set: function(newValue) {
        if (Hash.isHashed(newValue)) {
          return newValue;
        } else {
          return Hash.generate(newValue);
        }
      }
    }
  });
  return mongoose.model('User', User);
};
